from __future__ import annotations

import altair as alt
import pandas as pd
import streamlit as st

import backend.database as db
import backend.documents as docs

from .common import get_user_profile, go_to, logo_tag, render_portal_nav


def render():
    profile = get_user_profile()
    render_portal_nav("history")

    st.markdown(
        f"""
        <div class="page-header-card">
            <div class="header-main">
                <div class="header-brand">{logo_tag(44)}<span>Learning History</span></div>
                <div class="header-sub">Track usage, competency signals, and recent learning artefacts</div>
            </div>
            <div class="header-user">{profile['display_name']}<br><span>{profile['role']} · {profile['staff_id']}</span></div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    with st.sidebar:
        if st.button("Dashboard", use_container_width=True):
            go_to("menu")
        st.markdown("---")
        st.markdown("**Filter Records**")
        st.date_input("Date Range")
        st.multiselect("Activity Type", ["Quiz", "Chat Session", "Exam"], default=["Quiz", "Chat Session"])
        st.info("System Access Level: Staff (Read-Only)")

    history_messages = st.session_state.get("assistant_messages", [])
    saved_questions = db.count_questions()
    doc_count = docs.count_documents()

    st.markdown("<div class='section-label'>Performance Overview</div>", unsafe_allow_html=True)
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.markdown("<div class='metric-card'><div class='metric-label'>Study Hours</div><div class='metric-value'>12.5h</div></div>", unsafe_allow_html=True)
    with c2:
        st.markdown("<div class='metric-card'><div class='metric-label'>Modules Completed</div><div class='metric-value'>5 / 8</div></div>", unsafe_allow_html=True)
    with c3:
        st.markdown(f"<div class='metric-card'><div class='metric-label'>Saved Questions</div><div class='metric-value'>{saved_questions}</div></div>", unsafe_allow_html=True)
    with c4:
        st.markdown(f"<div class='metric-card'><div class='metric-label'>Chat Turns</div><div class='metric-value'>{len(history_messages)}</div></div>", unsafe_allow_html=True)

    st.write("")
    if "show_history_advisory" not in st.session_state:
        st.session_state["show_history_advisory"] = False
    if st.button("Generate AI Advisory Report", type="primary"):
        st.session_state["show_history_advisory"] = True

    if st.session_state["show_history_advisory"]:
        advisory_html = (
            '<div class="advisory-report">'
            '<div class="advisory-head">'
            '<div><div class="panel-kicker">AI Advisory Report</div>'
            '<div class="advisory-title">Learning Progress &amp; Preceptor Guidance</div></div>'
            '<span class="advisory-band">On Track</span>'
            '</div>'
            '<div class="advisory-comment">'
            f'<div class="advisory-comment-head">{logo_tag(26)}<span>AI Preceptor Comment</span></div>'
            f"<p>{profile['display_name']} has maintained <b>steady, consistent engagement</b> "
            'over the past week, with the strongest activity around knowledge retrieval and '
            'question-authoring. Daily study time is well distributed and competency scores '
            'in <b>Privacy</b> and <b>MSE</b> are excellent.</p>'
            '<p>The main opportunity for growth is <b>Ethics</b>, which currently trails the '
            'other domains. Translating frequent chat-based learning into completed assessment '
            'modules would also help convert engagement into measurable competency.</p>'
            '<p class="advisory-signoff">— Generated by Clinical-BERT-V4 · For supervisory review</p>'
            '</div>'
            '<div class="advisory-cols">'
            '<div class="advisory-col strengths">'
            '<div class="advisory-col-label">Key Strengths</div>'
            '<ul><li>Consistent daily engagement</li>'
            '<li>High Privacy &amp; MSE competency</li>'
            '<li>Active use of knowledge retrieval</li></ul>'
            '</div>'
            '<div class="advisory-col focus">'
            '<div class="advisory-col-label">Areas to Develop</div>'
            '<ul><li>Strengthen Ethics competency</li>'
            '<li>Complete remaining modules (5 / 8)</li>'
            '<li>Convert chat learning into practice</li></ul>'
            '</div>'
            '</div>'
            '<div class="advisory-actions">'
            '<div class="advisory-col-label">Recommended Next Steps</div>'
            '<p>Pair the competency exam with a targeted review of recent question-bank items, '
            'and prioritise an Ethics-focused module to reinforce overall exam readiness.</p>'
            '</div>'
            '</div>'
        )
        st.markdown(advisory_html, unsafe_allow_html=True)

    left, right = st.columns(2)
    with left:
        with st.container(border=True):
            st.markdown("<div class='section-label'>Daily Activity (Hours)</div>", unsafe_allow_html=True)
            data_hours = pd.DataFrame(
                {"Day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], "Hours": [1.5, 2.2, 0.5, 3.0, 1.0, 2.5, 1.8]}
            )
            base = alt.Chart(data_hours).encode(x=alt.X("Day", sort=None), y="Hours")
            st.altair_chart(
                base.mark_area(opacity=0.24, color="#4db6c7") + base.mark_line(color="#0d5c73") + base.mark_circle(size=64, color="#0d5c73"),
                use_container_width=True,
            )
    with right:
        with st.container(border=True):
            st.markdown("<div class='section-label'>Competency Scores</div>", unsafe_allow_html=True)
            data_scores = pd.DataFrame(
                {"Topic": ["MSE", "Safety", "Pharma", "Privacy", "Ethics", "Documents"], "Score": [92, 78, 85, 95, 70, min(100, 60 + doc_count * 6)]}
            )
            base = alt.Chart(data_scores).encode(x=alt.X("Topic", sort=None), y="Score")
            st.altair_chart(base.mark_bar(color="#0d5c73") + base.mark_text(dy=-6, color="#16333f").encode(text="Score"), use_container_width=True)

    with st.container(border=True):
        st.markdown("<div class='section-label'>Activity Log</div>", unsafe_allow_html=True)
        rows = [
            {"Date": "2026-06-30", "Type": "Assistant", "Module / Topic": "AI Learning Assistant", "Result": f"{saved_questions} saved questions"},
            {"Date": "2026-06-29", "Type": "Documents", "Module / Topic": "Knowledge Base", "Result": f"{doc_count} source document(s) available"},
            {"Date": "2026-06-28", "Type": "Exam", "Module / Topic": "Mental State Examination", "Result": "92% (PASS)"},
            {"Date": "2026-06-27", "Type": "Chat", "Module / Topic": "Anxiety Symptoms", "Result": "Completed"},
            {"Date": "2026-06-26", "Type": "Quiz", "Module / Topic": "Safety Protocols", "Result": "80% (PASS)"},
        ]
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

    st.markdown("<div class='section-label' style='margin-top:1rem;'>Session Transcripts & Certificates</div>", unsafe_allow_html=True)
    with st.expander("2026-06-28 | EXAM: Mental State Examination (MSE)"):
        st.success("PASS (92%)")
        st.info("Instructor Note: Excellent identification of behavioural cues. Review speech rate definitions.")
        st.button("Download PDF", key="history_cert")

    with st.expander("2026-06-27 | CHAT: Symptoms of Anxiety Protocol"):
        st.markdown("<div class='transcript-user'>User: What are the physical symptoms of a panic attack?</div>", unsafe_allow_html=True)
        st.markdown("<div class='transcript-bot'>AI Agent: Common physical symptoms include palpitations, sweating, trembling, shortness of breath, and chest pain.</div>", unsafe_allow_html=True)

    with st.expander("2026-06-26 | QUIZ: Safety Protocols Module 1"):
        st.warning("PASS (80%) - Review recommended")
        st.write("Weak Area: **Fire Safety Evacuation Routes**.")

    st.markdown("<div class='portal-footer'>System ID: IMH-LMS-V2.4 · Authorized Use Only</div>", unsafe_allow_html=True)
